language: node_js
sudo: false
dist: trusty
node_js:
  - "node"
  - "12"
  - "10"
  - "8"
  - "4"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - >
    node_version=$(node -v);
    if  [ ${node_version:1:1} = 6 ]; then
        npm i tap@13;
    elif  [ ${node_version:1:1} = 4 ]; then
        npm i tap@11;
    fi
script:
  - npm run test:ci
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT